---
title: "hw4"
format: html
editor: visual
---

# Load Data读取数据

```{r}
#空间数据
library(sf)
World <- st_read("../wk4/World_Countries_(Generalized)_9029012925078512962.geojson")
World
```

```{r}
#GII数据
library(readr)
library(janitor)
hdr_data <- read_csv("../wk4/HDR23-24_Composite_indices_complete_time_series.csv")
hdr_data <- hdr_data %>% 
  clean_names()
hdr_data
```

# Data Selection数据筛选

```{r}
library(dplyr)
GII <- hdr_data %>%
  select(iso3,country,region,gii_2010, gii_2019)
GII
```

# Data Processing数据处理
## Calculate GII Difference计算GII差值

```{r}
GII <- GII %>%
  mutate(gii_diff = gii_2010 - gii_2019)
GII
```
## 加载World国家代码
```{r}
library(countrycode)
library(dplyr)
World <- World %>%
  mutate(iso3 = countrycode(COUNTRY, origin = "country.name", destination = "iso3c"))
World
```

# Merge Data合并数据

```{r}
library(dplyr)
library(sf)

World_diff <- World %>%  #World作为主数据
  left_join(GII, by = c("iso3" = "iso3"))  #合并GII_diff
print(World_diff)
```

# Plot绘图

```{r}
library(ggplot2)
library(sf)
library(RColorBrewer) 

ggplot(data = World_diff) +
  geom_sf(aes(fill = cut(gii_diff,breaks = c(-Inf,-0.3, -0.1, 0.0, 0.1, 0.3, 0.5, Inf))), color = "black") + 
  scale_fill_manual(
    values = brewer.pal(7, "YlGnBu"),
    name = "GII Difference between 2010-2019",
    labels = c("< -0.3", "-0.3 to -0.1", "-0.1 to 0.0", "0.0 to 0.1", "0.1 to 0.3", "0.3 to 0.5", "> 0.5"),
    na.value = NA) + 
  labs(title = "Difference in GII Index 2010-2019") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5)  # 标题居中
  )
```
